# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8924c86a460e0e0c2aa77585741794f3c12ae2dc90e80bc0db9c899a209536a7e281f9a32dccafcb2a4cbb46eb2d942b44277da01304b42b6dba61fcce58e606

test:
  secret_key_base: 91948d16cc842c2a2a758ec1feef6f69677a0e5ea16d46f0cfba21353afb841ea5d9a0463aaa68af832c9294fd4a22a6a47d12ee854f5a17acd97e6b30227305

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
